Added method in MeasurementService + added unit test + refactored DTO…
OntdekIT/Software-BackEnd pull request #66
Opened 2023-11-01 13:08 UTC by Lars-v-Delft

… conversion in measurementService

2023-11-06 11:04 UTC, nepp95 requested changes

2023-11-06 11:04 UTC, nepp95 commented on ClimateChecker/src/main/java/Ontdekstation013/ClimateChecker/features/measurement/endpoint/MeasurementController.java
> +    public List<MeasurementDTO> getAt(
Functienamen zijn niet heel consequent. Backend getMeasurementsAt, hier getAt wat eigenlijk niks zegt over wat het doet. getLatestMeasurements is bijvoorbeeld vrij duidelijk. Je haalt de laatste measurements op. Zoiets willen we hierbij denk ik ook zien.

2023-11-06 11:04 UTC, nepp95 commented on ClimateChecker/src/main/java/Ontdekstation013/ClimateChecker/features/measurement/endpoint/MeasurementController.java
> +    public List<MeasurementDTO> getAt(
Hetzelfde geldt voor de functies op andere plekken (unittests)

2023-11-08 13:20 UTC, Lars-v-Delft commented on ClimateChecker/src/main/java/Ontdekstation013/ClimateChecker/features/measurement/endpoint/MeasurementController.java
> +    public List<MeasurementDTO> getAt(
Veranderd naar getMeasurementsAtTime() en getMeasurementsAtTime_ClosestToSpecifiedTime()

2023-11-08 14:08 UTC, nepp95 requested changes
Ff dat ene puntje fixen en dan is ie ready to go

2023-11-08 14:08 UTC, nepp95 commented on ClimateChecker/src/test/java/Ontdekstation013/ClimateChecker/measurement/MeasurementUnitTests.java
> +//    private MeasurementController measurementController;
Commented code kan gewoon weg. Je hebt het hierboven al gefixed ;)

2023-11-13 08:59 UTC, merged